### PR TITLE
Do you even know what you're doing? 

### PR DESCRIPTION
**Pull request by MCPEPIG**
1. pocketmine\plugin\PluginLoader does NOT exist.
2. You do NOT need PlayerCommandPreproccessEvent for this plugin...
3. The P in Player and the I in Item should NOT be lowercase
4. Why is it so messy...
5. No code for what you want the plugin to do? :stuck_out_tongue_winking_eye: Well, too bad, I'm not giving you code...

### CODE REVIEW

**Comment by MCPEPIG** [comment]
Oh and your other Anvil plugin is even messier and has 1, 2, & 3.

**Comment by TahaTheHacker** [comment]
But it works. and this is not ready. and those spaces are not needed.

**Comment by TahaTheHacker** [comment]
try it yourself

**Comment by TahaTheHacker** [comment]
i just made a copy of the other one and i will finish it later. so that's why..

**Comment by MCPEPIG** [comment]
It's wat too messy

**Comment by TahaTheHacker** [comment]
i am going to use those things i put.

**Comment by TahaTheHacker** [comment]
i will keep this :3

**Comment by TahaTheHacker** [comment]
:3 anyway i am merging it..

**Pull request merged**
